param(
    [string]$OutputDir = (Join-Path $PSScriptRoot "tmp")
)

$ErrorActionPreference = "Stop"

function Resolve-Tool([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    if ($env:VULKAN_SDK) {
        $candidate = Join-Path $env:VULKAN_SDK "Bin\$Name.exe"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    $scoopCandidate = Join-Path $env:USERPROFILE "scoop\apps\vulkan\current\Bin\$Name.exe"
    if (Test-Path $scoopCandidate) {
        return $scoopCandidate
    }
    return $null
}

# Fallback compiler: the Android NDK ships glslc (shader-tools), the same
# toolchain the depth-prime shaders use. Flags are translated in Invoke-Glsl.
function Resolve-NdkGlslc {
    $sdkRoot = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { Join-Path $env:LOCALAPPDATA "Android\Sdk" }
    $ndkDir = Join-Path $sdkRoot "ndk"
    if (Test-Path $ndkDir) {
        foreach ($ndk in (Get-ChildItem $ndkDir -Directory | Sort-Object Name -Descending)) {
            $candidate = Join-Path $ndk.FullName "shader-tools\windows-x86_64\glslc.exe"
            if (Test-Path $candidate) {
                return $candidate
            }
        }
    }
    return $null
}

function Invoke-Glsl([string]$Stage, [string]$Source, [string]$Output, [string[]]$Defines) {
    if ($script:glslang) {
        $glslArgs = @("-V", "-S", $Stage)
        foreach ($d in $Defines) { $glslArgs += "-D$d" }
        $glslArgs += @("-o", $Output, $Source)
        & $script:glslang @glslArgs | Out-Host
        if ($LASTEXITCODE -ne 0) { throw "glslangValidator failed for $Output" }
    }
    else {
        $stageName = if ($Stage -eq "vert") { "vertex" } else { "fragment" }
        $glslcArgs = @("-fshader-stage=$stageName", "--target-env=vulkan1.0")
        foreach ($d in $Defines) { $glslcArgs += "-D$d" }
        $glslcArgs += @("-o", $Output, $Source)
        & $script:glslc @glslcArgs | Out-Host
        if ($LASTEXITCODE -ne 0) { throw "glslc failed for $Output" }
    }
    if ($script:spirvVal) {
        & $script:spirvVal $Output
        if ($LASTEXITCODE -ne 0) { throw "spirv-val failed for $Output" }
    }
}

function Write-SpvInclude([string]$Path, [string]$Prefix, [array]$Variants) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("// Generated by generate_vulkan_picture_shaders.ps1")
    $lines.Add("")
    for ($i = 0; $i -lt $Variants.Count; ++$i) {
        $bytes = [System.IO.File]::ReadAllBytes($Variants[$i])
        $lines.Add("static const unsigned int $($Prefix)$i[$($bytes.Length / 4)] = {")
        $words = New-Object System.Collections.Generic.List[string]
        for ($j = 0; $j -lt $bytes.Length; $j += 4) {
            $word = [BitConverter]::ToUInt32($bytes, $j)
            $words.Add(("0x{0:x8}u" -f $word))
        }
        for ($j = 0; $j -lt $words.Count; $j += 8) {
            $take = [Math]::Min(8, $words.Count - $j)
            $lines.Add("    " + (($words.GetRange($j, $take)) -join ", ") + ",")
        }
        $lines.Add("};")
        $lines.Add("")
    }
    $lines.Add("static const unsigned int *${Prefix}_code[$($Variants.Count)] = {")
    $lines.Add("    " + ((0..($Variants.Count - 1) | ForEach-Object { "$Prefix$_" }) -join ", "))
    $lines.Add("};")
    $lines.Add("static const int ${Prefix}_size[$($Variants.Count)] = {")
    $lines.Add("    " + (($Variants | ForEach-Object { [System.IO.File]::ReadAllBytes($_).Length }) -join ", "))
    $lines.Add("};")
    Set-Content -Path $Path -Value ($lines -join "`n") -Encoding ASCII
}

$script:glslang = Resolve-Tool "glslangValidator"
$script:spirvVal = Resolve-Tool "spirv-val"
$script:glslc = $null
if (-not $script:glslang) {
    $script:glslc = Resolve-NdkGlslc
    if (-not $script:glslc) {
        throw "Neither glslangValidator (PATH/VULKAN_SDK/scoop) nor NDK glslc (shader-tools) was found"
    }
    Write-Host "glslangValidator not found - using NDK glslc: $script:glslc"
}
if (-not $script:spirvVal) {
    Write-Host "spirv-val not found - skipping SPIR-V validation"
}

New-Item -ItemType Directory -Force $OutputDir | Out-Null
$workDir = Join-Path $OutputDir "vulkan_picture_spirv_work"
New-Item -ItemType Directory -Force $workDir | Out-Null

$vsSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

struct DisplayEye { mat4x4 mMatrix_CamPrj; };
layout (std140, row_major, binding=4) uniform DisplayState
{
    DisplayEye mEye[2];
    vec2       mResolution;
} display;

// Eye selection: multipass uploads BOTH eyes' matrices once per frame and
// switches PassState.mID per eye pass - same convention as the paint VS
// (iid = pass.mID). mEye[0] hardcoded here rendered the right eye with the
// left eye's projection.
layout (std140, binding=5) uniform PassState
{
    int mID;
    int kk1;
    int kk2;
    int kk3;
} pass;

layout(location=0) in vec3 in_position;
layout(location=1) in vec3 in_normal;
layout(location=0) out vec3 out_direction;

// 0 = normal projected depth, 1 = reverse-Z far backdrop, 2 = less/equal far backdrop.
layout(constant_id = 0) const uint hostDepthBackdropMode = 0u;

void main()
{
    vec3 viewer_position = (layer.mLayerToViewer * vec4(in_position, 1.0)).xyz;
    out_direction = normalize(in_position);
    gl_Position = display.mEye[pass.mID].mMatrix_CamPrj * vec4(viewer_position, 1.0);
    if (hostDepthBackdropMode == 1u)
    {
        gl_Position.z = 0.0;
    }
    else if (hostDepthBackdropMode == 2u)
    {
        gl_Position.z = gl_Position.w;
    }
}
'@

$fsSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

layout(binding = 0) uniform sampler2D pictureTexture;
layout(location=0) in vec3 in_direction;
layout(location=0) out vec4 out_color;

// Diagnostic, off unless IMM_UNITY_VK_PIC_DEBUG is set. 1 = solid magenta at
// full alpha, bypassing the texture sample entirely. This is the one test that
// cannot be misread: if the sky turns magenta the geometry, pipeline, descriptor
// set and blend state are all sound and the fault is in sampling; if it stays
// black the fragments never survive at all and the fault is upstream of the
// shader. Every CPU-side probe reports success either way, which is exactly why
// this defect survived five rounds of instrumentation.
layout(constant_id = 0) const uint pictureDebugMode = 0u;

const float k_pi = 3.1415927;

void main()
{
    if (pictureDebugMode == 1u)
    {
        out_color = vec4(1.0, 0.0, 1.0, 1.0);
        return;
    }
    vec3 nor = normalize(in_direction);
    if (pictureDebugMode >= 2u)
    {
        // 2 = the texture's RGB with alpha forced opaque. If the picture appears,
        // sampling works and only the alpha channel is wrong.
        // 3 = the sampled ALPHA as greyscale, opaque. White = alpha 1 (so the
        // fault is downstream), black = alpha 0 (the alpha is what kills it).
        vec2 duv = vec2(0.5 + 0.5 * atan(nor.x, -nor.z) / k_pi, acos(clamp(nor.y, -1.0, 1.0)) / k_pi);
        vec4 dtexel = texture(pictureTexture, duv);
        // 4 = layer.mOpacity as greyscale. Modes 2 and 3 proved the texture is
        // sound, so the only remaining factor in the alpha is the uniform. Black
        // here means mOpacity arrives as zero despite the CPU logging 1.000, and
        // that is a uniform plumbing bug, not a content one.
        if (pictureDebugMode == 4u) { out_color = vec4(vec3(layer.mOpacity), 1.0); return; }
        out_color = (pictureDebugMode == 2u) ? vec4(dtexel.rgb, 1.0) : vec4(vec3(dtexel.a), 1.0);
        return;
    }
    vec2 uv = vec2(0.5 + 0.5 * atan(nor.x, -nor.z) / k_pi, acos(clamp(nor.y, -1.0, 1.0)) / k_pi);
    vec4 texel = texture(pictureTexture, uv);
// Drawing::ColorSpace is { Linear = 0, Gamma = 1 } (drawing.h), and
// LayerRendererPicture::Init selects the fragment variant with
// fsIndex = static_cast<int>(colorSpace). These shaders had the test the wrong
// way round - they applied the gamma->linear conversion when colorSpace was
// LINEAR, which is our configuration. Every picture was therefore raised to the
// 2.2 power once too often: 360sky averages 29/255, and pow(0.113, 2.2) is
// 2/255, so it drew fully opaque and perfectly black against a black
// background. The brighter the source the less it showed - which is why the
// white 360 and the logo survived while every dark environment vanished.
#if COLOR_SPACE == 1
    vec3 color = pow(texel.rgb, vec3(2.2));
#else
    vec3 color = texel.rgb;
#endif
    float alpha = texel.a * layer.mOpacity;
    out_color = vec4(color, alpha);
}
'@

$vsPath = Join-Path $workDir "shader_pip360Equirect_vk.vert"
$fsPath = Join-Path $workDir "shader_pip360Equirect_vk.frag"
Set-Content -Path $vsPath -Value $vsSource -NoNewline -Encoding ASCII
Set-Content -Path $fsPath -Value $fsSource -NoNewline -Encoding ASCII

$vs2DSource = @'
#version 460

// World-placed 2D picture quad, mirroring the GLES shader_pi2D_vs path:
// unit corners scaled by unSize (aspect, 1) in layer space, transformed by
// mLayerToViewer then the current eye's projection. The old version emitted
// raw NDC positions - every 2D picture rendered as a fullscreen head-locked
// overlay ("glued to my eyes").

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

struct DisplayEye { mat4x4 mMatrix_CamPrj; };
layout (std140, row_major, binding=4) uniform DisplayState
{
    DisplayEye mEye[2];
    vec2       mResolution;
} display;

layout (std140, binding=5) uniform PassState
{
    int mID;
    int kk1;
    int kk2;
    int kk3;
} pass;

// Picture renderer constants: unSize.xy = (aspect ratio, 1).
layout (std140, binding=9) uniform PictureConstants
{
    vec4 unSize;
} constants;

layout(location=0) out vec2 out_uv;

void main()
{
    vec2 corners[6] = vec2[](
        vec2(-1.0, -1.0),
        vec2( 1.0, -1.0),
        vec2( 1.0,  1.0),
        vec2(-1.0, -1.0),
        vec2( 1.0,  1.0),
        vec2(-1.0,  1.0)
    );
    vec2 c = corners[gl_VertexIndex];
    vec3 opos = vec3(constants.unSize.xy * c, 0.0);
    vec3 viewer_position = (layer.mLayerToViewer * vec4(opos, 1.0)).xyz;
    out_uv = 0.5 + 0.5 * c * vec2(1.0, -1.0);
    gl_Position = display.mEye[pass.mID].mMatrix_CamPrj * vec4(viewer_position, 1.0);
}
'@

$fs2DSource = @'
#version 460

layout (std140, row_major, binding=3) uniform LayersState
{
    mat4x4 mLayerToViewer;
    float  mLayerToViewerScale;
    float  mOpacity;
    float  mkUnused;
    float  mDrawInTime;
    vec4   mAnimParams;
    vec4   mKeepAlive[2];
    uint   mID;
} layer;

layout(binding = 0) uniform sampler2D pictureTexture;
layout(location=0) in vec2 in_uv;
layout(location=0) out vec4 out_color;

// See the 360 shader: solid magenta when IMM_UNITY_VK_PIC_DEBUG is set. The 2D
// path is known to render (the Oculus logo), so this doubles as the control -
// if 2D goes magenta and 360 stays black, the debug path itself is proven live.
layout(constant_id = 0) const uint pictureDebugMode = 0u;

void main()
{
    if (pictureDebugMode == 1u)
    {
        out_color = vec4(1.0, 0.0, 1.0, 1.0);
        return;
    }
    if (pictureDebugMode >= 2u)
    {
        vec4 dtexel = texture(pictureTexture, in_uv);
        if (pictureDebugMode == 4u) { out_color = vec4(vec3(layer.mOpacity), 1.0); return; }
        out_color = (pictureDebugMode == 2u) ? vec4(dtexel.rgb, 1.0) : vec4(vec3(dtexel.a), 1.0);
        return;
    }
    vec4 texel = texture(pictureTexture, in_uv);
// Same inversion as the 360 shader: the squaring approximates gamma->linear and
// belongs on the Gamma branch, not the Linear one.
#if COLOR_SPACE == 1
    vec3 color = texel.rgb * texel.rgb;
#else
    vec3 color = texel.rgb;
#endif
    out_color = vec4(color, texel.a * layer.mOpacity);
}
'@

$vs2DPath = Join-Path $workDir "shader_pi2D_vk.vert"
$fs2DPath = Join-Path $workDir "shader_pi2D_vk.frag"
Set-Content -Path $vs2DPath -Value $vs2DSource -NoNewline -Encoding ASCII
Set-Content -Path $fs2DPath -Value $fs2DSource -NoNewline -Encoding ASCII

$vsVariants = New-Object System.Collections.Generic.List[string]
$fsVariants = New-Object System.Collections.Generic.List[string]
$vs2DVariants = New-Object System.Collections.Generic.List[string]
$fs2DVariants = New-Object System.Collections.Generic.List[string]

$vsOut = Join-Path $workDir "shader_pip360Equirect_vs_vk.spv"
Invoke-Glsl "vert" $vsPath $vsOut @()
$vsVariants.Add($vsOut)

for ($colorSpace = 0; $colorSpace -le 1; ++$colorSpace) {
    $fsOut = Join-Path $workDir "shader_pip360Equirect_fs_vk_c${colorSpace}.spv"
    Invoke-Glsl "frag" $fsPath $fsOut @("COLOR_SPACE=$colorSpace")
    $fsVariants.Add($fsOut)
}

$vs2DOut = Join-Path $workDir "shader_pi2D_vs_vk.spv"
Invoke-Glsl "vert" $vs2DPath $vs2DOut @()
$vs2DVariants.Add($vs2DOut)

for ($colorSpace = 0; $colorSpace -le 1; ++$colorSpace) {
    $fs2DOut = Join-Path $workDir "shader_pi2D_fs_vk_c${colorSpace}.spv"
    Invoke-Glsl "frag" $fs2DPath $fs2DOut @("COLOR_SPACE=$colorSpace")
    $fs2DVariants.Add($fs2DOut)
}

Write-SpvInclude (Join-Path $OutputDir "shader_pip360Equirect_vs_spirv.inc") "shader_pip360Equirect_vs_spirv" $vsVariants
Write-SpvInclude (Join-Path $OutputDir "shader_pip360Equirect_fs_spirv.inc") "shader_pip360Equirect_fs_spirv" $fsVariants
Write-SpvInclude (Join-Path $OutputDir "shader_pi2D_vs_spirv.inc") "shader_pi2D_vs_spirv" $vs2DVariants
Write-SpvInclude (Join-Path $OutputDir "shader_pi2D_fs_spirv.inc") "shader_pi2D_fs_spirv" $fs2DVariants
